// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string             `json:"id"`
	Author    string             `json:"author"`
	Content   string             `json:"content"`
	CreatedAt string             `json:"createdAt"`
	PostID    string             `json:"postId"`
	Post      *Post              `json:"post"`
	ParentID  *string            `json:"parentId,omitempty"`
	Replies   *CommentConnection `json:"replies"`
}

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postId"`
	Author   string  `json:"author"`
	Content  string  `json:"content"`
	ParentID *string `json:"parentId,omitempty"`
}

type CreatePostInput struct {
	Author        string `json:"author"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	AllowComments bool   `json:"allowComments"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID            string             `json:"id"`
	Author        string             `json:"author"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	CreatedAt     string             `json:"createdAt"`
	AllowComments bool               `json:"allowComments"`
	Comments      *CommentConnection `json:"comments"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Node   *Post  `json:"node"`
	Cursor string `json:"cursor"`
}

type Query struct {
}
